version: '3.9'

services:
    postgres:
        image: postgres:latest
        ports:
            - 5432:5432

        environment:
            - POSTGRES_PASSWORD=banana12
            - POSTGRES_USER=admin
            - POSTGRES_DB=url_db


    s3-storage:
        image: localstack/localstack:0.12.5
        environment:
            # permite más servicios separados por comas
            - SERVICES=s3
            - DEBUG=1
            - DEFAULT_REGION=eu-west-1
            - AWS_ACCESS_KEY_ID=test
            - AWS_SECRET_ACCESS_KEY=test
        ports:
            - 4566:4566
        volumes:
            - './volumes/s3-storage/.init:/docker-entrypoint-initaws.d'
            - './volumes/s3-storage/.localstack:/tmp/localstack'
